name: Kamo-BranchTesting

on:
  push:
    branches:
      - Kamo_Kitchen

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install build dependencies
      run: sudo apt-get update -q && sudo apt-get install -y g++ make

    - name: Clean project
      run: make clean

    - name: Build project
      run: make

    - name: Run tests
      run: make run

    - name: Install cppcheck
      run: sudo apt-get install -y cppcheck

    - name: Upload cppcheck results
      uses: actions/upload-artifact@v2
      with:
        name: cppcheck-results
        path: cppcheck-results.txt

    - name: Check Coding Standards
      run: |
        # Check naming standards using grep
        if grep -r --exclude=cppcheck-results.txt --include=*.cpp --include=*.h \
          -E '(?<=[^\w])myVariable|calculateValue\(' .; then
          echo "ERROR: Naming standards violation"
          exit 1
        fi
        if grep -r --exclude=cppcheck-results.txt --include=*.cpp --include=*.h \
          -E '(?<=[^\w])MyClass|MyStruct\(' .; then
          echo "ERROR: PascalCase class and type names violation"
          exit 1
        fi
        if grep -r --exclude=cppcheck-results.txt --include=*.cpp --include=*.h \
          -E '(?<=[^\w])MAX_VALUE' .; then
          echo "ERROR: UPPERCASE constants violation"
          exit 1
        fi
        if grep -r --exclude=cppcheck-results.txt --include=*.cpp --include=*.h \
          -E '(?<=[^\w])m_memberVariable' .; then
          echo "ERROR: Member variable prefix violation"
          exit 1
        fi

        # Check format standards using shellcheck
        find . -type f -name "*.sh" -exec shellcheck {} \;
        fi
