name: Victor-BranchTesting

on:
  push:
    branches:
      - Victor-FloorComponent

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install build dependencies
      run: sudo apt-get install -y g++ make

    - name: Clean project
      run: make clean

    - name: Build project
      run: make

    - name: Run tests
      run: make run

    - name: Install cppcheck
      run: sudo apt-get install -y cppcheck

    - name: Run cppcheck
      run: |
        cppcheck --language=c++ --std=c++11 --enable=all --inconclusive . --template="[{file}:{line}] {severity}: {message}" --verbose 2> cppcheck-results.txt

    - name: Upload cppcheck results
      uses: actions/upload-artifact@v2
      with:
        name: cppcheck-results
        path: cppcheck-results.txt

    - name: Download gdrive
      run: |
        curl -Lo gdrive https://github.com/gdrive-org/gdrive/releases/download/2.1.0/gdrive-linux-x64
        chmod +x gdrive
      env:
        GDRIVE_KEY: ${{ secrets.TESTGOOGLEDRIVE }}

    - name: Upload executable to Google Drive
      run: |
        gdrive upload --file program
      env:
        GDRIVE_KEY: ${{ secrets.TESTGOOGLEDRIVE }}
